'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RADAR.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CompatibilityBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CompatibilityBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property emailtestPBSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emailtestPBSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lookupbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lookupbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RADAR_Clear() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RADAR_Clear", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Users_Police_icon_24_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Users_Police_icon_24_d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Users_Police_icon_24_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Users_Police_icon_24_l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Very_Basic_Cancel_icon_24_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Very_Basic_Cancel_icon_24_d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Very_Basic_Cancel_icon_24_r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Very_Basic_Cancel_icon_24_r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Very_Basic_Download_icon_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Very_Basic_Download_icon_d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Very_Basic_Download_icon_g() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Very_Basic_Download_icon_g", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Very_Basic_Folder_icon_24_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Very_Basic_Folder_icon_24_d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Very_Basic_Folder_icon_24_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Very_Basic_Folder_icon_24_l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Very_Basic_Search_icon_24_d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Very_Basic_Search_icon_24_d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Very_Basic_Search_icon_24_l() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Very_Basic_Search_icon_24_l", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wwwpb_radarnet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wwwpb_radarnet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wwwpb_radarnet_g() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wwwpb_radarnet_g", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
