'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace RadarWebService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.pb-radar.net/", ConfigurationName:="RadarWebService.RadarStatsSoap")>  _
    Public Interface RadarStatsSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.pb-radar.net/SendStats", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub SendStats(ByVal AuthKey As String, ByVal StatsDS As System.Data.DataTable, ByVal IndexID As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.pb-radar.net/SendPBSS", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub SendPBSS(ByVal AuthKey As String, ByVal ImageAsBase64Str As String, ByVal ServerGuid As String, ByVal ServerName As String, ByVal HeroName As String, ByVal ImageNum As String, ByVal ImageDate As String, ByVal IndexID As String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface RadarStatsSoapChannel
        Inherits RadarWebService.RadarStatsSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RadarStatsSoapClient
        Inherits System.ServiceModel.ClientBase(Of RadarWebService.RadarStatsSoap)
        Implements RadarWebService.RadarStatsSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub SendStats(ByVal AuthKey As String, ByVal StatsDS As System.Data.DataTable, ByVal IndexID As String) Implements RadarWebService.RadarStatsSoap.SendStats
            MyBase.Channel.SendStats(AuthKey, StatsDS, IndexID)
        End Sub
        
        Public Sub SendPBSS(ByVal AuthKey As String, ByVal ImageAsBase64Str As String, ByVal ServerGuid As String, ByVal ServerName As String, ByVal HeroName As String, ByVal ImageNum As String, ByVal ImageDate As String, ByVal IndexID As String) Implements RadarWebService.RadarStatsSoap.SendPBSS
            MyBase.Channel.SendPBSS(AuthKey, ImageAsBase64Str, ServerGuid, ServerName, HeroName, ImageNum, ImageDate, IndexID)
        End Sub
    End Class
End Namespace
